Add explicit casts from PIO_offset to int
This is needed to avoid compilation errors like this:

/Users/sacks/esmf/esmf0/src/Infrastructure/Mesh/src/ESMCI_ESMFMesh_Util.C:588:21: error: non-constant-expression cannot be narrowed from type 'MPI_Offset' (aka 'long long') to 'int' in initializer list [-Wc++11-narrowing]
  int gdimlen2D[2]={elementCount,maxNodePElement};